name: 股票監控

on:
  schedule:
    - cron: '*/5 1-6 * * 1-5' # 台灣時間 09:00 - 14:00 每5分
  workflow_dispatch:          # 允許手動按按鈕測試

# 👇 關鍵 1：給予機器人「寫入權限」，讓它可以記錄今天已通知過 (記憶功能)
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      
      - run: pip install -r requirements.txt
      
      - env:
          # 👇 關鍵修改 2：這裡的名字一定要跟 main.py 裡寫的一模一樣！
          # 左邊是給 Python 看的名字 : 右邊是讀取 GitHub Secrets 的倉庫
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py
